language: python
branches:
  only:
  - master
  except:
  - gh-pages
python:
  - "3.6"
# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
virtualenvs:
  system_site_packages: true
# command to run tests
script: python3.6 pytest.py || python pytest.py